name: PrestaShop Auto Tests Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  autotests:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v1    
    
      - name: Run Postman-Newman API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: PrestaShop_collection.postman_collection.json
          reporters: cli

      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}

      - name: Run JMeter Tests
        id: run-jmeter
        uses: rbhadti94/apache-jmeter-action@v0.3.1
        with:
          testFilePath: Prestashop_Test_Plan.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/

